SAMS/Controllers/AttendanceReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAMS.Models;
using SAMS.ViewModels;
using SAMS.Repository.AttendanceRepository;
using SAMS.Repository.ReportRepository;
using SAMS.Core;

namespace SAMS.Controllers
{
    [AuthorizeUser(Roles = "Admin,Teacher")]
    public class AttendanceReportController : Controller
    {
        private AttendanceRepository _repo;
        private ReportRepository _reportRepo;
        private ApplicationDbContext db = new ApplicationDbContext();
        public AttendanceReportController()
        {
            _repo = new AttendanceRepository();
            _reportRepo = new ReportRepository();
        }
        // GET: Attendance
        public async Task<ActionResult> Index()
        {
            var list = await _repo.GetModules();
            List<SelectListItem> ModuleDDL = list.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString()
            }).ToList();
            ModuleDDL.Insert(0, new SelectListItem { Text = "Select Module", Value = "" });
            ViewBag.ModuleDDL = ModuleDDL;

            ViewBag.TypeList = new List<SelectListItem>{
                //new SelectListItem { Text = "Select ", Value = "" },
                //new SelectListItem { Text = "Daily", Value = "Daily" },
                //new SelectListItem { Text = "Weekly", Value = "Weekly" },
                //new SelectListItem { Text = "Monthly", Value = "Monthly" }
            };
            return View();
        }


        // GET: Attendance/Details/5
        public async Task<ActionResult> Details(StudentReport data)
        {
            if (data == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            List<AttendanceReport> report = await _reportRepo.AttendanceReport(data);

            if (report == null)
            {
                return HttpNotFound();
            }
            return View(report);
        }

        // GET: Attendance/Create
        public async Task<ActionResult> Create()
        {
            AttendanceViewModel model = new AttendanceViewModel();

            if (HttpContext.IsDebuggingEnabled)
            {
                model.CourseList = new List<SelectListItem>(){
                new SelectListItem(){Text = "Business Administration(BBA)", Value = "1"},
                new SelectListItem(){Text = "Information Technology(BIT)", Value = "2"},
            };
                model.SemesterList = new List<SelectListItem>(){
                new SelectListItem(){ Text = "Semester 1", Value = "1" },
                new SelectListItem(){ Text = "Semester 2", Value = "2" },
                new SelectListItem(){ Text = "Semester 3", Value = "3" },
                new SelectListItem(){ Text = "Semester 4", Value = "4" },
                new SelectListItem(){ Text = "Semester 5", Value = "5" },
                new SelectListItem(){ Text = "Semester 6", Value = "6" },
                new SelectListItem(){ Text = "Semester 7", Value = "7" },
                new SelectListItem(){ Text = "Semester 8", Value = "8" }
            };
            }
            else
            {
                var courses = await _repo.GetCourses();
                model.CourseList = courses.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }).ToList();
                var semesters = await _repo.GetSemesters();
                model.SemesterList = semesters.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }).ToList();
            }

            model.ClassList = new List<SelectListItem>();

            return View(model);
        }

        // POST: Attendance/Create
        [HttpPost]
        public async Task<ActionResult> Create(AttendanceMaster attendanceMaster)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!HttpContext.IsDebuggingEnabled)
                    {
                        await _repo.SaveAttendance(attendanceMaster);
                    }
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return View(attendanceMaster);
        }

        [HttpGet]
        public async Task<JsonResult> GetCourseList()
        {
            try
            {
                List<SAMS.Models.Course> list;
                list = await _repo.GetCourses();

                var ddl = list.Select(a => new
                {
                    Text = a.Name,
                    Value = a.Id
                }).ToList();
                return Json(ddl, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { IsError = true, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        public async Task<JsonResult> GetTimetableList(int courseId, int semesterId)
        {
            try
            {
                SAMS.Models.AttendanceMaster param = new SAMS.Models.AttendanceMaster()
                    {
                        CourseId = courseId,
                        SemesterId = semesterId,
                        Day = (int)DateTime.Now.DayOfWeek
                    };
                List<SAMS.Models.Timetable> list;
                if (HttpContext.IsDebuggingEnabled)
                {
                    list = new List<Models.Timetable>()
                {
                    new Models.Timetable{Id=1, ClassDetails= "Data Algorithms | 10:00-11:00 | Sunday"},
                    new Models.Timetable{Id=1, ClassDetails= "Descrete Logics | 11:00-12:00 | Sunday"}
                };
                }
                else
                    list = await _repo.GetTimetable(param);

                var ddl = list.Select(a => new
                {
                    Text = a.ClassDetails,
                    Value = a.Id
                }).ToList();
                return Json(ddl, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { IsError = true, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public async Task<JsonResult> GetStudentList(int moduleId)
        {
            try
            {
                List<SAMS.Models.Student> students;
                students = await _repo.GetStudents(moduleId);
                var list = students.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList();
                return Json(list, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { IsError = true, Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAMS/Views/AttendanceReport/Details.cshtml
@model List<SAMS.Models.AttendanceReport>

<div>
    <h4>Student Attendance Report</h4>
    <hr />
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Student Name</th>
                <th>Roll Number</th>
                <th>Present Days</th>
                <th>Late Days</th>
                <th>Absent Days</th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>@Html.DisplayFor(model => model[i].StudentName)</td>
                    <td>@Html.DisplayFor(model => model[i].RollNumber)</td>
                    <td>@Html.DisplayFor(model => model[i].PresentDays)</td>
                    <td>@Html.DisplayFor(model => model[i].LateDays)</td>
                    <td>@Html.DisplayFor(model => model[i].AbsentDays)</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

SAMS/Views/AttendanceReport/Index.cshtml
@model SAMS.Models.StudentReport


@using (Html.BeginForm("Details", "AttendanceReport"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Student Attendance Report</h4>
        <hr />
        @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.LabelFor(model => model.ModuleId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.ModuleId, (IEnumerable<SelectListItem>)ViewBag.ModuleDDL, new { @class = "form-control" , @id="modules"})
                    @Html.ValidationMessageFor(model => model.ModuleId)
                </div>
                @Html.LabelFor(model => model.StudentId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.StudentId, (IEnumerable<SelectListItem>)ViewBag.TypeList, new { @class = "form-control" , @id="students"})
                    @Html.ValidationMessageFor(model => model.FromDate)
                </div>
                @*@Html.LabelFor(model => model.ReportType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.ReportType, (IEnumerable<SelectListItem>)ViewBag.TypeList, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FromDate)
                </div>*@
            </div>
            <div class="form-group col-md-12">
                @Html.LabelFor(model => model.FromDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.TextBoxFor(model=>model.FromDate, new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.FromDate)
                </div>

                @Html.LabelFor(model => model.ToDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.ToDate, new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(model => model.ToDate)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Show Report" class="btn btn-default" />
                </div>
            </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
    $(document).ready(function () {

        $('#FromDate').datepicker({
            dateFormat: "yy/mm/dd",
            changeMonth: true,
            changeYear: true,
            yearRange: "-60:+0"
        });
        $('#ToDate').datepicker({
            dateFormat: "yy/mm/dd",
            changeMonth: true,
            changeYear: true,
            yearRange: "-60:+0"

        });
        $("#modules").change(function () {
            var module = $("#modules").val();
            var _classes = $("#students");
            _classes.empty();
            $.ajax({
                method: "GET",
                url: '@Url.Action("GetStudentList")',
                data: {
                    moduleId: module
                },
                success: function (data) {
                    if (data) {
                        _classes.append($('<option/>', { value: "-1", text: "All Students" }))
                        $.each(data, function (index, item) {
                            _classes.append($('<option/>', { value: item.Value, text: item.Text }))
                        });
                    }
                }
            })
        });

       
        })
</script>

}