SAMS/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAMS;
using SAMS.Logic;
using SAMS.Models;
using System.Threading.Tasks;
using System.Data.SqlClient;
using SAMS.Repository.AttendanceRepository;
using SAMS.Core;

namespace SAMS.Controllers
{
    [AuthorizeUser(Roles = "Admin,Teacher")]
    public class ModuleController : Controller
    {
        private ModuleLogic _logic;
        private CourseLogic _logicCourse;
        AttendanceRepository _attendanceRepo;

        public ModuleController()
        {
            _logic = new ModuleLogic();
            _logicCourse = new CourseLogic();
            _attendanceRepo = new AttendanceRepository();
        }

        // GET: /Timetable/
        public async Task<ActionResult> Index()
        {
            List<Module> lst = await _logic.GetModules();
            return View(lst);
        }

        // GET: /Timetable/Details/5
        public async Task<ActionResult> Details(int id)
        {

            Module obj = await _logic.GetModule(id);
            if (obj == null)
            {
                return HttpNotFound();
            }
            return View(obj);
        }

        // GET: /Timetable/Create
        public async Task<ActionResult> Create()
        {
            List<Course> lstCourses = await _logicCourse.GetCourses();
            List<Semester> lstSemester = await _attendanceRepo.GetSemesters();
            ViewBag.CourseId = new SelectList(lstCourses, "Id", "Name");
            ViewBag.SemesterId = new SelectList(lstSemester, "Id", "Name");
            return View();
        }

        // POST: /Timetable/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create( Module module)
        {

            List<Course> lstCourses = await _logicCourse.GetCourses();
            List<Semester> lstSemester = await _attendanceRepo.GetSemesters();
            ViewBag.CourseId = new SelectList(lstCourses, "Id", "Name");
            ViewBag.SemesterId = new SelectList(lstSemester, "Id", "Name");
            bool status = false;
            string message = string.Empty;
            if (ModelState.IsValid)
            {
                try
                {
                    status = await _logic.InsertUpdateModule(module);
                }
                catch (SqlException ex)
                {

                    message = ex.Message;
                }
                catch (Exception)
                {

                    message = "Unexpected error was found";
                }

            }
            if (status)
            {
                return RedirectToAction("Index");

            }
            else
            {
                ViewBag.Message = message;
                return View(module);
            }

        }

        // GET: /Timetable/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            Module obj = await _logic.GetModule(id);
            List<Course> lstCourses = await _logicCourse.GetCourses();
            List<Semester> lstSemester = await _attendanceRepo.GetSemesters();
            ViewBag.CourseId = new SelectList(lstCourses, "Id", "Name", obj.CourseId);
            ViewBag.SemesterId = new SelectList(lstSemester, "Id", "Name", obj.SemesterId);
            return View(obj);
        }

        // POST: /Timetable/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit( Module module)
        {

            Module obj = await _logic.GetModule(module.Id);
            List<Course> lstCourses = await _logicCourse.GetCourses();
            List<Semester> lstSemester = await _attendanceRepo.GetSemesters();
            ViewBag.CourseId = new SelectList(lstCourses, "Id", "Name", obj.CourseId);
            ViewBag.SemesterId = new SelectList(lstSemester, "Id", "Name", obj.SemesterId);
            bool status = false;
            string message = string.Empty;
            if (ModelState.IsValid)
            {
                try
                {
                    status = await _logic.InsertUpdateModule(module);
                }
                catch (SqlException ex)
                {

                    message = ex.Message;
                }
                catch (Exception)
                {

                    message = "Unexpected error was found";
                }

            }
            if (status)
            {
                return RedirectToAction("Index");

            }
            else
            {
                ViewBag.Message = message;
                return View(module);
            }

        }

        // GET: /Timetable/Delete/5
        [AuthorizeUser(Roles = "Admin")]
        public async Task<ActionResult> Delete(int id)
        {
            Module obj = await _logic.GetModule(id);
            if (obj == null)
            {
                return HttpNotFound();
            }
            return View(obj);
        }

        // POST: /Timetable/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeUser(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                bool status = await _logic.DeleteModule(id);
                return RedirectToAction("Index");
            }
            catch (SqlException ex)
            {
                if (ex.Errors.Count > 0)
                {
                    if (ex.Errors[0].Number == 547)
                    {
                        ViewBag.Message = "This data can not be deleted,because it is in use.";
                        return View();
                    }

                }
                ViewBag.Message = "Database error occurred";
                return View();

            }
            catch (Exception)
            {
                ViewBag.Message = "Something went wrong while deleting the record.";
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                // _logic.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAMS/Views/Module/Create.cshtml
@model SAMS.Models.Module

@{
    ViewBag.Title = "Create";
}

<h3>Module Create</h3>

@*<style>
        .custom-form-control{
            width: 50%;
        }
    </style>*@


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

      
        @Html.ValidationSummary(true)

        <div class="form-group row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control col-md-2" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.Code, new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.Code, new { @class = "form-control col-md-2" })
                @Html.ValidationMessageFor(model => model.Code)

            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.Credit, new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.Credit, new { @class = "form-control col-md-2" })
                @Html.ValidationMessageFor(model => model.Credit)

            </div>
        </div>



        <div class="form-group row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Level, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Level, new { @class = "form-control custom-form-control" })
                @Html.ValidationMessageFor(model => model.Level)

            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.CourseId, "CourseId", new { @class = "control-label" })
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control custom-form-control" })
                @Html.ValidationMessageFor(model => model.CourseId)
            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.SemesterId, new { @class = "control-label" })
                @Html.DropDownList("SemesterId", null, htmlAttributes: new { @class = "form-control custom-form-control" })
                @Html.ValidationMessageFor(model => model.SemesterId)
            </div>
       
        </div>

        <div class="form-group col-md-12">
            <div class=" col-md-offset-2 col-md-2">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div id="divMessage" style="line-height:5px" class=" col-md-8">
                @ViewBag.Message
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
    $(document).ready(function () {

            var message = '@ViewBag.Message';
            if (!(message == null || message == '' || message == undefined)) {
                $("#divMessage").addClass('alert alert-danger');
                $(".alert").fadeOut(3000);
            }

        });
</script>
}

SAMS/Views/Module/Delete.cshtml
@model SAMS.Models.Module

@{
    ViewBag.Title = "Delete";
}

<h3>Module Delete</h3>

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Credit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Level)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Level)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SemesterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SemesterName)
        </dd>



    </dl>

    <div id="divMessage" style="line-height:20px;background-color:red;font-weight:bold" class=" col-md-8">
        @ViewBag.Message
    </div>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SAMS/Views/Module/Details.cshtml
@model SAMS.Models.Module
@{
    ViewBag.Title = "Details";
}

<h3>Module Details</h3>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Credit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Level)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Level)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SemesterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SemesterName)
        </dd>



    </dl>

</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SAMS/Views/Module/Edit.cshtml
@model SAMS.Models.Module

@{
    ViewBag.Title = "Create";
}

<h3>Module Edit</h3>

@*<style>
        .custom-form-control{
            width: 50%;
        }
    </style>*@


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        

        @Html.ValidationSummary(true)

        <div class="form-group row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control col-md-2" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.Code, new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.Code, new { @class = "form-control col-md-2" })
                @Html.ValidationMessageFor(model => model.Code)

            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.Credit, new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.Credit, new { @class = "form-control col-md-2" })
                @Html.ValidationMessageFor(model => model.Credit)

            </div>
        </div>



        <div class="form-group row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Level, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Level, new { @class = "form-control custom-form-control" })
                @Html.ValidationMessageFor(model => model.Level)

            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.CourseId, "CourseId", new { @class = "control-label" })
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control custom-form-control" })
                @Html.ValidationMessageFor(model => model.CourseId)
            </div>
            <div class="col-md-4">
                @Html.LabelFor(model => model.SemesterId, new { @class = "control-label" })
                @Html.DropDownList("SemesterId", null, htmlAttributes: new { @class = "form-control custom-form-control" })
                @Html.ValidationMessageFor(model => model.SemesterId)
            </div>

        </div>

        <div class="form-group col-md-12">
            <div class=" col-md-offset-2 col-md-2">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
            <div id="divMessage" style="line-height:5px" class=" col-md-8">
                @ViewBag.Message
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>
    $(document).ready(function () {


    
            var message = '@ViewBag.Message';
            if (!(message == null || message == '' || message == undefined)) {
                $("#divMessage").addClass('alert alert-danger');
                $(".alert").fadeOut(3000);
            }

        });
</script>
}

SAMS/Views/Module/Index.cshtml
@model IEnumerable<SAMS.Models.Module>



@{
    ViewBag.Title = "Index";
}

<h3>Module Index</h3>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-responsive table-hover table-bordered table-condensed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Credit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Level)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CourseName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SemesterName)
        </th>
      
       
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SemesterId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Credit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Level)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SemesterName)
            </td>
            
            <td>
                <a href="@Url.Action("Edit", "Module", new { id = item.Id })" class="btn btn-info btn-sm" title="Edit">

                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                </a>
                <a href="@Url.Action("Delete", "Module", new { id = item.Id })" class="btn btn-danger btn-sm" title="Delete">

                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>

                <a href="@Url.Action("Details", "Module", new { id = item.Id })" class="btn btn-success btn-sm" title="Details">

                    <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                </a>
            </td>
        </tr>
    }

</table>